/* =========================================================================
   Sistema de Gestão Escolar — Firebird 5.0
   Script de criação do banco + schema (DDL) + carga inicial (seed) opcional.
   Convenções: DDD tático — SERIE_TURMA é o agregado que contém MATRICULA.
   ========================================================================= */

CREATE DATABASE 'GestaoEscolar.fdb'
    USER 'SYSDBA' PASSWORD 'masterkey'
    PAGE_SIZE 8192
    DEFAULT CHARACTER SET UTF8;

COMMIT;

/* -------------------------------------------------------------------------
   1. CIDADE
   ------------------------------------------------------------------------- */
CREATE TABLE CIDADE (
    ID          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME        VARCHAR(100) NOT NULL,
    UF          CHAR(2) NOT NULL,
    CONSTRAINT UQ_CIDADE_NOME_UF UNIQUE (NOME, UF)
);

/* -------------------------------------------------------------------------
   2. ALUNO
   ------------------------------------------------------------------------- */
CREATE TABLE ALUNO (
    ID                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME              VARCHAR(120) NOT NULL,
    DATA_NASCIMENTO   DATE NOT NULL,
    CPF               VARCHAR(14),
    NOME_RESPONSAVEL  VARCHAR(120),
    TELEFONE          VARCHAR(20),
    EMAIL             VARCHAR(120),
    CIDADE_ID         INTEGER NOT NULL,
    ATIVO             BOOLEAN DEFAULT TRUE NOT NULL,
    DATA_CADASTRO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ALUNO_CIDADE FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID),
    CONSTRAINT UQ_ALUNO_CPF UNIQUE (CPF)
);

/* -------------------------------------------------------------------------
   3. SERIE
   ------------------------------------------------------------------------- */
CREATE TABLE SERIE (
    ID            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME          VARCHAR(60) NOT NULL,
    NIVEL_ENSINO  VARCHAR(20) NOT NULL,
    ORDEM         SMALLINT NOT NULL,
    CONSTRAINT CK_SERIE_NIVEL CHECK (NIVEL_ENSINO IN
        ('INFANTIL', 'FUNDAMENTAL_I', 'FUNDAMENTAL_II', 'MEDIO'))
);

/* -------------------------------------------------------------------------
   4. TURMA
   ------------------------------------------------------------------------- */
CREATE TABLE TURMA (
    ID                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME                VARCHAR(10) NOT NULL,
    TURNO               VARCHAR(10) NOT NULL,
    CAPACIDADE_MAXIMA   SMALLINT NOT NULL,
    CONSTRAINT CK_TURMA_TURNO CHECK (TURNO IN ('MANHA', 'TARDE', 'NOITE')),
    CONSTRAINT CK_TURMA_CAPACIDADE CHECK (CAPACIDADE_MAXIMA > 0)
);

/* -------------------------------------------------------------------------
   5. SERIE_TURMA — agregado "montagem" (raiz DDD; MATRICULA é filha dele)
   ------------------------------------------------------------------------- */
CREATE TABLE SERIE_TURMA (
    ID           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SERIE_ID     INTEGER NOT NULL,
    TURMA_ID     INTEGER NOT NULL,
    ANO_LETIVO   SMALLINT NOT NULL,
    ATIVO        BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT FK_SERIETURMA_SERIE FOREIGN KEY (SERIE_ID) REFERENCES SERIE (ID),
    CONSTRAINT FK_SERIETURMA_TURMA FOREIGN KEY (TURMA_ID) REFERENCES TURMA (ID),
    CONSTRAINT UQ_SERIETURMA_ANO UNIQUE (SERIE_ID, TURMA_ID, ANO_LETIVO)
);

/* -------------------------------------------------------------------------
   6. MATRICULA — entidade filha de SERIE_TURMA
   ------------------------------------------------------------------------- */
CREATE TABLE MATRICULA (
    ID                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ALUNO_ID           INTEGER NOT NULL,
    SERIE_TURMA_ID     INTEGER NOT NULL,
    NUMERO_MATRICULA   VARCHAR(20) NOT NULL,
    DATA_MATRICULA     DATE DEFAULT CURRENT_DATE NOT NULL,
    STATUS             VARCHAR(15) DEFAULT 'ATIVA' NOT NULL,
    DATA_SITUACAO      DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT FK_MATRICULA_ALUNO FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO (ID),
    CONSTRAINT FK_MATRICULA_SERIETURMA FOREIGN KEY (SERIE_TURMA_ID) REFERENCES SERIE_TURMA (ID),
    CONSTRAINT UQ_MATRICULA_NUMERO UNIQUE (NUMERO_MATRICULA),
    CONSTRAINT CK_MATRICULA_STATUS CHECK (STATUS IN
        ('ATIVA', 'TRANCADA', 'TRANSFERIDA', 'CONCLUIDA', 'CANCELADA'))
);

COMMIT;

/* -------------------------------------------------------------------------
   Regra de negócio RN06 — "uma matrícula ativa por aluno por ano letivo"
   atravessa agregados (várias SERIE_TURMA possíveis no mesmo ano), então a
   aplicação (MatricularAlunoUseCase) já verifica isso antes de gravar.
   Este trigger é uma segunda linha de defesa no banco, para quem for testar
   o schema direto pelo isql/DBeaver sem passar pela aplicação.
   ------------------------------------------------------------------------- */
CREATE EXCEPTION EX_MATRICULA_DUPLICADA_NO_ANO
    'Aluno já possui matrícula ativa neste ano letivo.';

COMMIT;

SET TERM ^ ;

CREATE TRIGGER TRG_MATRICULA_UNICA_ANO FOR MATRICULA
    ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
    DECLARE VARIABLE V_ANO_LETIVO SMALLINT;
    DECLARE VARIABLE V_QTD INTEGER;
BEGIN
    IF (NEW.STATUS = 'ATIVA') THEN
    BEGIN
        SELECT ST.ANO_LETIVO
            FROM SERIE_TURMA ST
            WHERE ST.ID = NEW.SERIE_TURMA_ID
            INTO :V_ANO_LETIVO;

        SELECT COUNT(*)
            FROM MATRICULA M
            JOIN SERIE_TURMA ST ON ST.ID = M.SERIE_TURMA_ID
            WHERE M.ALUNO_ID = NEW.ALUNO_ID
              AND M.STATUS = 'ATIVA'
              AND ST.ANO_LETIVO = :V_ANO_LETIVO
              AND M.ID <> COALESCE(OLD.ID, -1)
            INTO :V_QTD;

        IF (V_QTD > 0) THEN
            EXCEPTION EX_MATRICULA_DUPLICADA_NO_ANO;
    END
END
^

SET TERM ; ^

COMMIT;

/* =========================================================================
   Carga inicial (seed) — dados de exemplo para começar a testar a aplicação
   sem precisar cadastrar tudo na mão. Apague este bloco se preferir o banco
   vazio.
   ========================================================================= */

INSERT INTO CIDADE (NOME, UF) VALUES ('São Paulo', 'SP');
INSERT INTO CIDADE (NOME, UF) VALUES ('Campinas', 'SP');
INSERT INTO CIDADE (NOME, UF) VALUES ('Belo Horizonte', 'MG');

INSERT INTO SERIE (NOME, NIVEL_ENSINO, ORDEM) VALUES ('1º Ano - Ensino Fundamental', 'FUNDAMENTAL_I', 1);
INSERT INTO SERIE (NOME, NIVEL_ENSINO, ORDEM) VALUES ('2º Ano - Ensino Fundamental', 'FUNDAMENTAL_I', 2);
INSERT INTO SERIE (NOME, NIVEL_ENSINO, ORDEM) VALUES ('9º Ano - Ensino Fundamental', 'FUNDAMENTAL_II', 9);

INSERT INTO TURMA (NOME, TURNO, CAPACIDADE_MAXIMA) VALUES ('A', 'MANHA', 30);
INSERT INTO TURMA (NOME, TURNO, CAPACIDADE_MAXIMA) VALUES ('B', 'TARDE', 25);

COMMIT;

INSERT INTO SERIE_TURMA (SERIE_ID, TURMA_ID, ANO_LETIVO, ATIVO)
    VALUES (1, 1, 2026, TRUE);
INSERT INTO SERIE_TURMA (SERIE_ID, TURMA_ID, ANO_LETIVO, ATIVO)
    VALUES (2, 2, 2026, TRUE);

COMMIT;

INSERT INTO ALUNO (NOME, DATA_NASCIMENTO, CPF, NOME_RESPONSAVEL, TELEFONE, EMAIL, CIDADE_ID)
    VALUES ('João Pedro Silva', '2019-03-14', '111.111.111-11', 'Maria Silva', '(11) 99999-0001', 'joao.silva@exemplo.com', 1);
INSERT INTO ALUNO (NOME, DATA_NASCIMENTO, CPF, NOME_RESPONSAVEL, TELEFONE, EMAIL, CIDADE_ID)
    VALUES ('Ana Beatriz Souza', '2018-07-22', '222.222.222-22', 'Carlos Souza', '(19) 99999-0002', 'ana.souza@exemplo.com', 2);

COMMIT;

INSERT INTO MATRICULA (ALUNO_ID, SERIE_TURMA_ID, NUMERO_MATRICULA, DATA_MATRICULA, STATUS, DATA_SITUACAO)
    VALUES (1, 1, '2026-000001', CURRENT_DATE, 'ATIVA', CURRENT_DATE);

COMMIT;
