/* =========================================================================
   Sistema de Gestão Escolar — Firebird 5.0
   Script de criação do banco + schema (DDL) + carga inicial (seed) opcional.
   Convenções: DDD tático — SERIE_TURMA é o agregado que contém MATRICULA.
   ========================================================================= */

CREATE DATABASE 'GestaoEscolar.fdb'
    USER 'SYSDBA' PASSWORD 'masterkey'
    PAGE_SIZE 8192
    DEFAULT CHARACTER SET UTF8;

COMMIT;

/* -------------------------------------------------------------------------
   1. CIDADE
   ------------------------------------------------------------------------- */
CREATE TABLE CIDADE (
    ID          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME        VARCHAR(100) NOT NULL,
    UF          CHAR(2) NOT NULL,
);

/* -------------------------------------------------------------------------
   2. ALUNO
   ------------------------------------------------------------------------- */
CREATE TABLE ALUNO (
    ID                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME              VARCHAR(120) NOT NULL,
    DATA_NASCIMENTO   DATE NOT NULL,
    CPF               VARCHAR(14),
    CIDADE_ID         INTEGER NOT NULL,
    CONSTRAINT FK_ALUNO_CIDADE FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID),
    CONSTRAINT UQ_ALUNO_CPF UNIQUE (CPF)
);


COMMIT;
